version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - run: git clone -b karsajobs << pipeline.trigger_parameters.github_app.repo_url >>

      - run:
          name: lint-dockerfile
          command: |
            git clone https://github.com/hadolint/hadolint \
              && cd hadolint \
              && cabal configure \
              && cabal build \
              && cabal install
            hadolint Dockerfile

      - run:
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)

      - run:
          name: build-app-karsajobs
          command: |
            echo $CR_PAT | docker login ghcr.io -u $GHCR_NAMESPACE --password-stdin
            docker tag karsajobs:latest ghcr.io/$GHCR_NAMESPACE/karsajobs:latest
            docker push ghcr.io/$GHCR_NAMESPACE/karsajobs:latest