version: 2.1
orbs:
  golang: circleci/go@2.2.0
  docker: circleci/docker@2.8.1

jobs:
  lint-dockerfile:
    jobs:
      - docker/hadolint:
          dockerfiles: path/to/Dockerfile
          executor-class: medium
          hadolint-tag: 2.2.0-debian

  test-app:
    executor: golang/default

    steps:
      - checkout

      - run:
          name: test-app
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: golang/default

    steps:
      - checkout

      - run:
          name: Container Login
          command: echo $CR_PAT | docker login ghcr.io -u $GHCR_NAMESPACE --password-stdin

      - run:
          name: Build and Push Image
          command: |
            docker build -t karsajobs:latest .
            docker tag karsajobs:latest ghcr.io/$GHCR_NAMESPACE/karsajobs:latest
            docker push ghcr.io/$GHCR_NAMESPACE/karsajobs:latest

workflows:
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs