version: 2.1
orbs:
  go: circleci/go@2.2.0
  docker: circleci/docker@2.8.1

jobs:
  lint-dockerfile:
    executor: docker/machine
    steps:
      - checkout
      - docker/hadolint:
          dockerfiles: ./Dockerfile

  test-app:
    executor:
      name: go/default
      tag: '1.23'
    steps:
      - checkout
      - go/with-cache:
          steps:
            - go/mod-download
            - go/test

  build-app-karsajobs:
    executor: docker/docker
        steps:
          - checkout
          - docker/check
          - docker/build:
              image: hasanqqsp/karsajobs
              tag: latest
              registry: ghcr.io
          - docker/push:
              digest-path: /tmp/digest.txt
              image: hasanqqsp/karsajobs
              registry: ghcr.io
              tag: latest
          - run:
              command: |
                echo "Digest is: $(</tmp/digest.txt)"

workflows:
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs